### ISSUE TITLE
consider adding OWASP ASVS

### ISSUE THREAD

**Issue by javabeanz** [hysnsec/DevSecOps-Studio#31]
OWASP ASVS is a great project to get your security requirements, controls and tests in one go documented.
It could be a valuable addition to the studio.

In any case :+1: great to see DevSecOps Studio as it is !

**Comment by teacheraio** [comment]
Thanks @javabeanz, nice timing! this will be added into next release 👍

**Comment by javabeanz** [comment]
thats super !

**Comment by secfigo** [comment]
We have decided against it, will be closing this issue now.
