### ISSUE TITLE
Gitlab-Runner issue

### ISSUE THREAD

**Issue by seccodingguy** [hysnsec/DevSecOps-Studio#45]
Before and after following the tutorial and re-running vagrant provision gitlab-runner:

TASK [gitlab-runner : Uninstall existing gitlab-runner shell runner] ***********
fatal: [gitlab-runner]: FAILED! => {"changed": true, "cmd": ["gitlab-runner", "unregister", "-n", "gitlab-runner"], "delta": "0:00:00.017641", "end": "2018-07-11 12:23:11.719244", "msg": "non-zero return code", "rc": 1, "start": "2018-07-11 12:23:11.701603", "stderr": "Running in system-mode.                           \u001b[0;m \n                                                  \u001b[0;m \n\u001b[31;1mFATAL: Could not find a runner with the name 'gitlab-runner'\u001b[0;m ", "stderr_lines": ["Running in system-mode.                           \u001b[0;m ", "                                                  \u001b[0;m ", "\u001b[31;1mFATAL: Could not find a runner with the name 'gitlab-runner'\u001b[0;m "], "stdout": "", "stdout_lines": []}

Also the gitlab.local/admin/runners Web GUI does not show the gitlab-runner as a provisioned Runner.

**Comment by secfigo** [comment]
Fixed in the new release, thank you for this report.
