### ISSUE TITLE
reference URL to Packer seems to have changed

### ISSUE THREAD

**Issue by meetinthemiddle-be** [hysnsec/DevSecOps-Studio#86]
When running `ansible-galaxy install -r requirements.yml`

`[WARNING]: - geerlingguy.ansible-role-packer was NOT installed successfully: - sorry, geerlingguy.ansible-role-packer was not found on https://galaxy.ansible.com/api/.`

**Comment by secfigo** [comment]
Fixed in #90 

thank you.
